### ISSUE TITLE
Inquiries regarding code implementation

### ISSUE THREAD

**Issue by sudaCode** [tjddus9597/HIER-CVPR23#1]
Thank you for making the code.

I attempted to use scripts file to **reproduce the results**. However, I have encountered disparities between my experimental results and those reported in your paper. I have only achieved a maximum **R@1 value of 67.98 on the CUB dataset** (CNN). 

This outcome has left me perplexed. So I want to ask if there are any other details that I haven't noticed.

**Comment by sung-yeon-kim** [comment]
First, thank u for interesting my work.
We're sorry to hear that the results were quite low compared to what we got.
Perhaps, there seems to be a difference in some setting, and I will check again what made this difference.

**Comment by sudaCode** [comment]
Excuse me, how's it going?

**Comment by sung-yeon-kim** [comment]
I am sorry for the delay in addressing this issue due to CVPR business trip. I'll fix the problem as soon as possible and leave a comment. I don't think it will take that long because it reproduces the results already obtained.

**Comment by sudaCode** [comment]
ok, thank u. Have a nice trip!

**Comment by sung-yeon-kim** [comment]
I confirmed that some options are different from the original script.
Please run the experiment again, correcting the warmup epoch to 0.
Below is a figure of the reproducing results, and we observed that the experiment with the script achieved higher performance than the reported result of the paper.

If you have any other questions, please leave a comment.

![image](https://github.com/tjddus9597/HIER-CVPR23/assets/20388245/6e2a9816-b93c-471f-9b3d-895fb5fcaf4e)

**Comment by sudaCode** [comment]
Yeah, It's true.  I didn't expect it to be the problem. Thanks for your reply.
